CREATE TABLE contacts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    lastname VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(30) NULL,
    dateCreate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dateUpdate DATETIME NULL DEFAULT CURRENT_TIMESTAMP
);